spring.application.name=taskpilot-ai

# ==========================
# Database
# ==========================
spring.datasource.url=mysql://root:iNamBiygqysewOjAZtmLOeFRPITNmMSC@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=iNamBiygqysewOjAZtmLOeFRPITNmMSC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================
# Groq AI
# ==========================
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

# ==========================
# Logging
# ==========================
logging.level.org.springframework.security=DEBUG